include $(MHMAKECONF)/scripts/build/paths.mak

ifndef DEBUG
DEBUG=0
endif
ifndef MAKESERVER
MAKESERVER=0
endif

default: all
.PHONY : default

#define some gnu make functions used in conditional compilation
EQ =$(if $(subst $(1)_,,$(2)_),0,1)
NE =$(if $(subst $(1)_,,$(2)_),1,0)
OR =$(subst 10,1,$(findstring 1,$(1))0)
AND=$(subst 01,0,$(findstring 0,$(1))1)
NOT=$(if $(findstring 0,$(1)),1,0)

CC        ?= cl /nologo
CPP       ?= $(CC)
CCFLAGS   += -c -GF -Gy -FS #-Wall

#CCFLAGS   += -wd4996 -wd4738
LINK      ?= link /nologo
LINKFLAGS += /INCREMENTAL:NO
ifeq ($(IS64),1)
AS=ml64
LINKFLAGS += /MACHINE:X64
OBJDIREXTRA=64
SSLSUFFIX=64
else
AS=ml
LINKFLAGS += /MACHINE:X86
SSLSUFFIX=32
endif
AR        ?= lib /nologo
RC        ?= rc
RCFLAGS   ?= /l 0x409

# Native Windows tools, overridable by the build environment.
PYTHON3   ?= python.exe
WIN_FLEX  ?= win_flex.exe
WIN_BISON ?= win_bison.exe
GPERF     ?= gperf.exe
PERL      ?= perl.exe
# mhmake's command parser cannot start a redirected recipe with a quoted
# executable. Launchers keep full tool paths (possibly containing spaces) in
# the environment and quote them inside cmd.exe instead.
PYTHON = $(MHMAKECONF)\tools\run-python.bat
FLEX = $(MHMAKECONF)\tools\run-flex.bat
BISON = $(MHMAKECONF)\tools\run-bison.bat
GPERF_COMMAND = $(MHMAKECONF)\tools\run-gperf.bat
BUILD_NATIVE = $(PYTHON) "$(MHMAKECONF)/tools/build_native.py"

SKIPHEADERS=string map stdlib.h stddef.h string.h stdio.h windows.h stdarg.h

ifeq ($(MAKESERVER),1)
OBJDIRPREFIX=serv
DEFINES += XKB_IN_SERVER XFree86Server HAVE_DIX_CONFIG_H 
else
DEFINES += XKB
endif

ifeq ($(NORELDBG),1)
# This all is here to avoid unnecessary rebuilds when switching between release and debug and MAKESERVER
OBJDIR?=obj$(OBJDIREXTRA)
DEBUG=0
MAKESERVER=0
endif

ifeq ($(DEBUG),1)
CCFLAGS   += -MDd -RTC1 -Od -GS -GR -Zi
LINKFLAGS += /DEBUG
OBJDIR ?= obj$(OBJDIREXTRA)\$(OBJDIRPREFIX)debug
NOSERVOBJDIR ?= obj$(OBJDIREXTRA)\debug
SERVOBJDIR ?= obj$(OBJDIREXTRA)\servdebug
DEFINES += _DEBUG DEBUG
RCFLAGS += -d "_DEBUG"
OPENSSLOBJDIR:=debug$(SSLSUFFIX)
else
CCFLAGS   += -MD -O2 -Ob2 -Oi -Ox -Oy -Ot -Zi -GL
DEFINES   +=  NDEBUG
LINKFLAGS += /OPT:REF /OPT:ICF /LTCG:STATUS
OBJDIR ?= obj$(OBJDIREXTRA)\$(OBJDIRPREFIX)release
NOSERVOBJDIR ?= obj$(OBJDIREXTRA)\release
SERVOBJDIR ?= obj$(OBJDIREXTRA)\servrelease
RCFLAGS += -d "NDEBUG"
AR += /LTCG
OPENSSLOBJDIR:=release$(SSLSUFFIX)
endif



DEFINES += WIN32 _WIN32 _WINDOWS WINDOWS _MBCS __i386__ __MINGW32__ _POSIX_ X_NOT_POSIX _TIMEVAL_DEFINED mode_t=int __STDC__
DEFINES += FAKEIT HAVE_CONFIG_H _BSD_SOURCE _WIN32_WINNT=_WIN32_WINNT_WINXP

TOPSRCDIR=$(COMPONENT_XORG_SERVER_DIR)

INCLUDES += . $(COMPONENT_OPENSSL_DIR)\include $(COMPONENT_OPENSSL_DIR)\$(OPENSSLOBJDIR)\include $(MHMAKECONF)/include $(MHMAKECONF)\pixman-1 $(COMPONENT_PTHREADS_DIR)
INCLUDES += $(TOPSRCDIR)\include $(TOPSRCDIR)\mi $(TOPSRCDIR)\mfb $(TOPSRCDIR)\hw\xfree86\common $(TOPSRCDIR)\render $(TOPSRCDIR)\miext\damage
INCLUDES += $(TOPSRCDIR)\damageext $(TOPSRCDIR)\randr $(TOPSRCDIR)\xfixes $(TOPSRCDIR)\Xi $(TOPSRCDIR)\fb $(TOPSRCDIR)\miext\cw
INCLUDES += $(TOPSRCDIR)\miext\shadow $(TOPSRCDIR)\miext\sync $(COMPONENT_ZLIB_DIR)
INCLUDES += $(MHMAKECONF)\include $(TOPSRCDIR)\Xext $(COMPONENT_PIXMAN_DIR)\pixman $(TOPSRCDIR)\present

SYSTEMLIBS ?= odbc32.lib odbccp32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib shlwapi.lib \
              oleaut32.lib uuid.lib odbc32.lib odbccp32.lib setupapi.lib winmm.lib ws2_32.lib wmcodecdspuuid.lib comctl32.lib opengl32.lib \
							synchronization.lib

BDFTOPCF=$(COMPONENT_BDFTOPCF_DIR)\$(OBJDIR)\bdftopcf.exe
MKFONTSCALE=$(COMPONENT_MKFONTSCALE_DIR)\$(OBJDIR)\mkfontscale.exe

all: $(OBJDIR)

ifeq ($(DEBUG),1)
PTHREADLIB:=$(COMPONENT_PTHREADS_DIR)\libpthreadVC3d$(OBJDIREXTRA).lib
ifeq ($(IS64),1)
FREETYPELIB:=$(COMPONENT_FREETYPE_DIR)\objs\x$(OBJDIREXTRA)\Debug\freetype.lib
else
FREETYPELIB:=$(COMPONENT_FREETYPE_DIR)\objs\Win32\Debug\freetype.lib
endif
OPENSSLLIB:=$(COMPONENT_OPENSSL_DIR)\debug$(SSLSUFFIX)\libssl.lib $(COMPONENT_OPENSSL_DIR)\debug$(SSLSUFFIX)\libcrypto.lib
else
PTHREADLIB:=$(COMPONENT_PTHREADS_DIR)\libpthreadVC3$(OBJDIREXTRA).lib
ifeq ($(IS64),1)
FREETYPELIB:=$(COMPONENT_FREETYPE_DIR)\objs\x$(OBJDIREXTRA)\Release\freetype.lib
else
FREETYPELIB:=$(COMPONENT_FREETYPE_DIR)\objs\Win32\Release\freetype.lib
endif
OPENSSLLIB:=$(COMPONENT_OPENSSL_DIR)\release$(SSLSUFFIX)\libssl.lib $(COMPONENT_OPENSSL_DIR)\release$(SSLSUFFIX)\libcrypto.lib
endif
ifeq ($(IS64),1)
XMLARCH=x64
else
XMLARCH=Win32
endif
ifeq ($(DEBUG),1)
XMLCONFIG=Debug
else
XMLCONFIG=Release
endif
LIBXMLLIB:=$(COMPONENT_LIBXML2_DIR)\build\$(XMLARCH)\$(XMLCONFIG)\libxml2.lib
LIBXMLINCLUDE:=$(COMPONENT_LIBXML2_DIR)\build\$(XMLARCH)\$(XMLCONFIG)\include
