ifneq ($(NORELDBG),1)
$(error NORELDBG should have been set to 1)
endif
ifneq ($(IS64),0)
$(error IS64 should have been set to 0, buld is independent on 64-bit)
endif

srcdir=.

format_srgb.c: format_srgb.py
	$(PYTHON) $(srcdir)/format_srgb.py > $@

u_format_gen := $(srcdir)/format/u_format_table.py
u_format_deps := $(srcdir)/format/u_format.yaml \
	$(srcdir)/format/u_format_pack.py \
	$(srcdir)/format/u_format_parse.py

format/u_format_gen.h: $(u_format_deps)
	@mkdir -p $(dir $@)
	$(PYTHON) $(u_format_gen) --enums $< > $@

format/u_format_pack.h: $(u_format_deps)
	@mkdir -p $(dir $@)
	$(PYTHON) $(u_format_gen) --header $< > $@

format/u_format_table.c: $(srcdir)/format/u_format_table.py $(srcdir)/format/u_format.yaml
	$(PYTHON) $(srcdir)/format/u_format_table.py $(srcdir)/format/u_format.yaml > $@

driconf_static_gen := driconf_static.py
driconf_static_deps := 00-mesa-defaults.conf

driconf_static.h: $(driconf_static_deps)
	$(PYTHON) $(driconf_static_gen) $^ $@

u_indices_gen.c: ../gallium/auxiliary/indices/u_indices_gen.py
	$(PYTHON) $< $@

u_unfilled_gen.c: ../gallium/auxiliary/indices/u_unfilled_gen.py
	$(PYTHON) $< $@

